/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab2;

import ds.AktyvumoBaluSistema;
import ds.Kursas;
import ds.Uzduotis;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;

/**
 *
 * @author pc
 */
public class DarbasKursas extends javax.swing.JFrame {

    private AktyvumoBaluSistema abs;
    DefaultListModel model = new DefaultListModel();

    public DarbasKursas(AktyvumoBaluSistema ab) {

        initComponents();
        abs = ab;
        dropdown_kursas.setModel(new DefaultComboBoxModel(abs.getDestytojas().getKursai().toArray()));
        Atnaujinti();
    }

    public void Atnaujinti() {
        if (!abs.getKursai().isEmpty()) {
            String[] strings = dropdown_kursas.getSelectedItem().toString().split(" ");
            list.removeAll();
            model.removeAllElements();
            for (Uzduotis u : abs.gautiKursa(strings[1].substring(1, strings[1].length() - 1)).getUzduotys()) {
                model.addElement(u);
            }
            list.setModel(model);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        dropdown_kursas = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        l_kodas = new javax.swing.JLabel();
        l_pavadinimas = new javax.swing.JLabel();
        l_aprasymas = new javax.swing.JLabel();
        l_data = new javax.swing.JLabel();
        tf1 = new javax.swing.JTextField();
        tf2 = new javax.swing.JTextField();
        tf3 = new javax.swing.JTextField();
        tf4 = new javax.swing.JTextField();
        prideti = new javax.swing.JButton();
        redaguoti = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        list = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Kurso informacija");

        jLabel2.setText("Kursas:");

        dropdown_kursas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        dropdown_kursas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dropdown_kursasActionPerformed(evt);
            }
        });

        jLabel3.setText("Kurso darbai:");

        jLabel4.setText("Pridėti uzduotį");

        l_kodas.setText("Kodas:");

        l_pavadinimas.setText("Pavadinimas:");

        l_aprasymas.setText("Aprašymas:");

        l_data.setText("Padaryti iki:");

        tf4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf4ActionPerformed(evt);
            }
        });

        prideti.setText("Pridėti");
        prideti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pridetiActionPerformed(evt);
            }
        });

        redaguoti.setText("Redaguoti");
        redaguoti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                redaguotiActionPerformed(evt);
            }
        });

        list.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(list);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dropdown_kursas, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(redaguoti))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(l_pavadinimas)
                                            .addComponent(l_aprasymas)
                                            .addComponent(l_data)
                                            .addComponent(l_kodas))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tf1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(tf2, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                                                .addComponent(tf3)
                                                .addComponent(tf4)))))
                                .addGap(0, 39, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(prideti)
                                .addContainerGap())))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(dropdown_kursas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(l_kodas)
                            .addComponent(tf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(l_pavadinimas)
                            .addComponent(tf2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(l_aprasymas)
                            .addComponent(tf3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(l_data)
                            .addComponent(tf4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(prideti))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(redaguoti)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dropdown_kursasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dropdown_kursasActionPerformed

        Atnaujinti();
    }//GEN-LAST:event_dropdown_kursasActionPerformed

    private void tf4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf4ActionPerformed

    private void pridetiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pridetiActionPerformed
        if (!abs.getKursai().isEmpty()) {
            try {

                if (tf1.getText().isEmpty()) {
                    l_kodas.setForeground(java.awt.Color.red);
                } else {
                    l_kodas.setForeground(java.awt.Color.BLACK);
                }
                if (tf2.getText().isEmpty() || tf2.getText().length()>40) {
                    l_pavadinimas.setForeground(java.awt.Color.red);
                } else {
                    l_pavadinimas.setForeground(java.awt.Color.BLACK);
                }
                if (tf3.getText().isEmpty() || tf3.getText().length()>40) {
                    l_aprasymas.setForeground(java.awt.Color.red);
                } else {
                    l_aprasymas.setForeground(java.awt.Color.BLACK);
                }
                if (tf4.getText().length() != 10) {
                    l_data.setForeground(java.awt.Color.red);
                } else {
                    l_data.setForeground(java.awt.Color.BLACK);
                }
                if (!tf2.getText().isEmpty() && !tf3.getText().isEmpty() && tf4.getText().length() == 10) {
                    if (tf2.getText().length() <= 40 && tf3.getText().length() <= 40) {
                        Uzduotis uzduotis = new Uzduotis(Integer.parseInt(tf1.getText()), "nematomas", tf2.getText(), tf3.getText(), tf4.getText());
                        String[] strings = dropdown_kursas.getSelectedItem().toString().split(" ");
                        // abs.gautiKursa(strings[1].substring(1,strings[1].length()-1)).pridetiUzduoti(abs,uzduotis);
                        Kursas kursas = abs.gautiKursa(strings[1].substring(1, strings[1].length() - 1));
                        kursas.getUzduotys().add(uzduotis);
                        abs.priskirtiUzduotiPrieKurso(uzduotis, kursas);
                        Atnaujinti();
                        tf1.setText("");
                        tf2.setText("");
                        tf3.setText("");
                        tf4.setText("");

                        l_kodas.setForeground(java.awt.Color.BLACK);
                    }
                }
            } catch (NumberFormatException e) {
                l_kodas.setForeground(java.awt.Color.red);
            }
        }
    }//GEN-LAST:event_pridetiActionPerformed

    private void redaguotiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_redaguotiActionPerformed
        if (!list.isSelectionEmpty()) {
            String[] strings = dropdown_kursas.getSelectedItem().toString().split(" ");
            String uzd = model.getElementAt(list.getSelectedIndex()).toString();

            String[] strings2 = uzd.split(" ");
            Kursas kursas = abs.gautiKursa(strings[1].substring(1, strings[1].length() - 1));
            DarbasUzduotis darbasUzduotis = new DarbasUzduotis(abs, kursas.gautiUzduoti(Integer.parseInt(strings2[0])), this);
            darbasUzduotis.setVisible(true);
        }
    }//GEN-LAST:event_redaguotiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DarbasKursas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DarbasKursas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DarbasKursas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DarbasKursas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the dialog */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> dropdown_kursas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel l_aprasymas;
    private javax.swing.JLabel l_data;
    private javax.swing.JLabel l_kodas;
    private javax.swing.JLabel l_pavadinimas;
    private javax.swing.JList<String> list;
    private javax.swing.JButton prideti;
    private javax.swing.JButton redaguoti;
    private javax.swing.JTextField tf1;
    private javax.swing.JTextField tf2;
    private javax.swing.JTextField tf3;
    private javax.swing.JTextField tf4;
    // End of variables declaration//GEN-END:variables
}
