/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab2;

import ds.AktyvumoBaluSistema;
import ds.Ikelimas;
import ds.Uzduotis;
import java.awt.Color;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;

/**
 *
 * @author pc
 */
public class DarbasUzduotis extends javax.swing.JFrame {

    private AktyvumoBaluSistema abs;
    private Uzduotis uzduotis;
    private DarbasKursas darbasKursas;
    private Ikelimas ikelimas;
    DefaultListModel model = new DefaultListModel();
    DefaultComboBoxModel model2 = new DefaultComboBoxModel();

    public DarbasUzduotis(AktyvumoBaluSistema ab, Uzduotis uzd, DarbasKursas dk) {
        initComponents();
        abs = ab;
        uzduotis = uzd;
        darbasKursas = dk;
        if (uzduotis.getIkelimai().size() != 0) {
            combo2.setModel(new DefaultComboBoxModel(uzduotis.getIkelimai().toArray()));
        }
        model2.addElement("matomas");
        model2.addElement("nematomas");
        model2.addElement("uzrakintas");
        combo.setModel(model2);
        AtnaujintiIkelima();
    }

    @Override
    public void dispose() {
        super.dispose(); //To change body of generated methods, choose Tools | Templates.
        darbasKursas.Atnaujinti();
    }

    @Override
    public void setVisible(boolean b) {
        super.setVisible(b); //To change body of generated methods, choose Tools | Templates.
        Atnaujinti();
        AtnaujintiIkelima();
    }

    void AtnaujintiIkelima() {
        l_ivertinimas.setForeground(Color.black);
        l_komentaras.setForeground(Color.black);
        if (uzduotis.getIkelimai().size() != 0) {
            String strings[] = combo2.getSelectedItem().toString().split(" ");
            ikelimas = uzduotis.gautiIkelima(Integer.parseInt(strings[0]));
            String strings2[] = ikelimas.getStudentas().toString().split(" ");
            vardas.setText(strings2[1] + " " + strings2[2]);
            kodas.setText(strings[0]);
            komentaras.setText(ikelimas.getKomentaras());
            ivertinimas.setText(ikelimas.getIvertinimas() + "");
        }
    }

    void Atnaujinti() {
        l_ivertinimas.setForeground(Color.black);
        l_komentaras.setForeground(Color.black);
        tekstas.setText(uzduotis.getStatusas());
        pavadinimas.setText(uzduotis.getPavadinimas());
        aprasymas.setText(uzduotis.getAprasymas());
        if (!uzduotis.getIkelimai().isEmpty()) {
            list.removeAll();
            model.removeAllElements();

            for (Ikelimas u : uzduotis.getIkelimai()) {
                model.addElement(u);
            }
            list.setModel(model);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        combo2 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        list = new javax.swing.JList<>();
        combo = new javax.swing.JComboBox<>();
        tekstas = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        vardas = new javax.swing.JLabel();
        l_ivertinimas = new javax.swing.JLabel();
        ivertinimas = new javax.swing.JTextField();
        l_komentaras = new javax.swing.JLabel();
        komentaras = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        kodas = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        pavadinimas = new javax.swing.JLabel();
        aprasymas = new javax.swing.JLabel();
        bendrasKomentaras = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Užduoties informacija");

        jLabel2.setText("Statusas:");

        jButton1.setText("Patvirtinti");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Ikelimai:");

        combo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo2ActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(list);

        combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboActionPerformed(evt);
            }
        });

        tekstas.setText("<tekstas>");

        jLabel4.setText("Atliko:");

        vardas.setText("-");

        l_ivertinimas.setText("Ivertinimas:");

        ivertinimas.setText("-");
        ivertinimas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ivertinimasActionPerformed(evt);
            }
        });

        l_komentaras.setText("Komentaras:");

        jButton2.setText("Patvirtinti");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel7.setText("Studento kodas:");

        kodas.setText("-");

        jLabel8.setText("Pavadinimas:");

        jLabel9.setText("Aprašymas:");

        pavadinimas.setText("<tekstas>");

        aprasymas.setText("<tekstas>");

        bendrasKomentaras.setText("Bendras komentaras");
        bendrasKomentaras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bendrasKomentarasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(combo2, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(l_komentaras)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(komentaras, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(bendrasKomentaras)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton2))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(l_ivertinimas)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel4))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(vardas)
                                            .addComponent(ivertinimas, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(kodas))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGap(18, 18, 18)))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(combo, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton1))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tekstas)
                                    .addComponent(pavadinimas)
                                    .addComponent(aprasymas))))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(pavadinimas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(aprasymas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tekstas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(combo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(vardas))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(kodas))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(l_ivertinimas)
                            .addComponent(ivertinimas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(komentaras, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(l_komentaras))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2)
                            .addComponent(bendrasKomentaras)))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        uzduotis.setStatusas(combo.getSelectedItem().toString());
        abs.AtnaujintiUzduoti(uzduotis);
        Atnaujinti();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void combo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo2ActionPerformed
        AtnaujintiIkelima();
    }//GEN-LAST:event_combo2ActionPerformed

    private void comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboActionPerformed

    private void ivertinimasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ivertinimasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ivertinimasActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            if (Integer.parseInt(ivertinimas.getText()) > 10 || 0 > Integer.parseInt(ivertinimas.getText())) {
                l_ivertinimas.setForeground(Color.red);
            } else {
                l_ivertinimas.setForeground(Color.black);
            }
            if (komentaras.getText().length() > 250) {
                l_komentaras.setForeground(Color.red);
            }

            if (uzduotis.getIkelimai().size() != 0 && Integer.parseInt(ivertinimas.getText()) <= 10 && Integer.parseInt(ivertinimas.getText()) >= 0 && 250 >= komentaras.getText().length()) {
                ikelimas.setIvertinimas(Integer.parseInt(ivertinimas.getText()));
                ikelimas.setKomentaras(komentaras.getText());
                if (ikelimas != null) {
                    abs.AtnaujintiIvertinima(ikelimas);
                    l_ivertinimas.setForeground(Color.black);
                    l_komentaras.setForeground(Color.black);
                }
            }
        } catch (NumberFormatException e) {
            l_ivertinimas.setForeground(Color.red);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void bendrasKomentarasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bendrasKomentarasActionPerformed
         if (komentaras.getText().length() > 250) {
                l_komentaras.setForeground(Color.red);
            }

            if (uzduotis.getIkelimai().size() != 0 && Integer.parseInt(ivertinimas.getText()) <= 10 && Integer.parseInt(ivertinimas.getText()) >= 0 && 250 >= komentaras.getText().length()) {
                
                if (ikelimas != null) {
                    for(Ikelimas i: uzduotis.getIkelimai()){
                         i.setKomentaras(komentaras.getText());
                         abs.AtnaujintiIvertinima(i);
                    }
                }
            }
    }//GEN-LAST:event_bendrasKomentarasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aprasymas;
    private javax.swing.JButton bendrasKomentaras;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> combo;
    private javax.swing.JComboBox<String> combo2;
    private javax.swing.JTextField ivertinimas;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel kodas;
    private javax.swing.JTextField komentaras;
    private javax.swing.JLabel l_ivertinimas;
    private javax.swing.JLabel l_komentaras;
    private javax.swing.JList<String> list;
    private javax.swing.JLabel pavadinimas;
    private javax.swing.JLabel tekstas;
    private javax.swing.JLabel vardas;
    // End of variables declaration//GEN-END:variables
}
