/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab2;

import ds.AktyvumoBaluSistema;

/**
 *
 * @author pc
 */
public class DestytojoPridejimas extends javax.swing.JDialog {

    private AktyvumoBaluSistema abs;

    /**
     * Creates new form DestytojoPridejimas
     */
    public DestytojoPridejimas(java.awt.Frame parent, AktyvumoBaluSistema ab) {
        super(parent, true);
        initComponents();
        abs = ab;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        l_kodas = new javax.swing.JLabel();
        f_kodas = new javax.swing.JTextField();
        l_vardas = new javax.swing.JLabel();
        f_vardas = new javax.swing.JTextField();
        f_pavarde = new javax.swing.JTextField();
        l_pavarde = new javax.swing.JLabel();
        ui_mygtukas_patvirtinti = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Destytojo pridejimas");
        setResizable(false);

        l_kodas.setText("Kodas:");

        f_kodas.setToolTipText("");
        f_kodas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f_kodasActionPerformed(evt);
            }
        });
        f_kodas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                f_kodasKeyReleased(evt);
            }
        });

        l_vardas.setText("Vardas:");

        f_vardas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f_vardasActionPerformed(evt);
            }
        });
        f_vardas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                f_vardasKeyReleased(evt);
            }
        });

        f_pavarde.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                f_pavardeKeyReleased(evt);
            }
        });

        l_pavarde.setText("Pavarde:");

        ui_mygtukas_patvirtinti.setText("Patvirtinti");
        ui_mygtukas_patvirtinti.setEnabled(false);
        ui_mygtukas_patvirtinti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ui_mygtukas_patvirtintiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(l_vardas)
                                    .addComponent(l_kodas)))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(l_pavarde)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(f_vardas, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(f_kodas, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(f_pavarde, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 43, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(ui_mygtukas_patvirtinti)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l_kodas)
                    .addComponent(f_kodas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(f_vardas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l_vardas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(f_pavarde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l_pavarde))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ui_mygtukas_patvirtinti)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void f_kodasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f_kodasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_f_kodasActionPerformed

    private void ui_mygtukas_patvirtintiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ui_mygtukas_patvirtintiActionPerformed
        String kodas = f_kodas.getText();
        String vardas = f_vardas.getText();
        String pavarde = f_pavarde.getText();
        abs.pridetiDestytoja(Integer.parseInt(kodas), vardas, pavarde);
        this.dispose();
    }//GEN-LAST:event_ui_mygtukas_patvirtintiActionPerformed

    private void f_kodasKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_f_kodasKeyReleased
        try {
            int kodas = Integer.parseInt(f_kodas.getText());
            if (f_vardas.getText().length() != 0 && f_vardas.getText().length() <= 40 && f_pavarde.getText().length() != 0 && f_pavarde.getText().length() <= 40) {
                ui_mygtukas_patvirtinti.setEnabled(true);
            } else {
                ui_mygtukas_patvirtinti.setEnabled(false);
            }
        } catch (NumberFormatException e) {
            ui_mygtukas_patvirtinti.setEnabled(false);
        }
    }//GEN-LAST:event_f_kodasKeyReleased

    private void f_vardasKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_f_vardasKeyReleased
        try {
            int kodas = Integer.parseInt(f_kodas.getText());
            if (f_vardas.getText().length() != 0 && f_vardas.getText().length() <= 40 && f_pavarde.getText().length() != 0 && f_pavarde.getText().length() <= 40) {
                ui_mygtukas_patvirtinti.setEnabled(true);
            } else {
                ui_mygtukas_patvirtinti.setEnabled(false);
            }
        } catch (NumberFormatException e) {
            ui_mygtukas_patvirtinti.setEnabled(false);
        }
    }//GEN-LAST:event_f_vardasKeyReleased

    private void f_pavardeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_f_pavardeKeyReleased
        try {
            int kodas = Integer.parseInt(f_kodas.getText());
            if (f_vardas.getText().length() != 0 && f_vardas.getText().length() <= 40 && f_pavarde.getText().length() != 0 && f_pavarde.getText().length() <= 40) {
                ui_mygtukas_patvirtinti.setEnabled(true);
            } else {
                ui_mygtukas_patvirtinti.setEnabled(false);
            }
        } catch (NumberFormatException e) {
            ui_mygtukas_patvirtinti.setEnabled(false);
        }
    }//GEN-LAST:event_f_pavardeKeyReleased

    private void f_vardasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f_vardasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_f_vardasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField f_kodas;
    private javax.swing.JTextField f_pavarde;
    private javax.swing.JTextField f_vardas;
    private javax.swing.JLabel l_kodas;
    private javax.swing.JLabel l_pavarde;
    private javax.swing.JLabel l_vardas;
    private javax.swing.JButton ui_mygtukas_patvirtinti;
    // End of variables declaration//GEN-END:variables
}
