/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab2;

import ds.AktyvumoBaluSistema;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JFileChooser;

/**
 *
 * @author pc
 */
public class DestytojoImport extends javax.swing.JDialog {

    private File f;
    private AktyvumoBaluSistema abs;

    /**
     * Creates new form DestytojoImport
     */
    public DestytojoImport(java.awt.Frame parent, AktyvumoBaluSistema ab) {
        super(parent, true);
        initComponents();
        abs = ab;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ui_tekstas_vardas = new javax.swing.JTextField();
        ui_mygtukas_pasirinkti = new javax.swing.JButton();
        ui_mygtukas_importuoti = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        ui_tekstas_vardas.setEditable(false);
        ui_tekstas_vardas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ui_tekstas_vardasActionPerformed(evt);
            }
        });
        ui_tekstas_vardas.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                ui_tekstas_vardasPropertyChange(evt);
            }
        });
        ui_tekstas_vardas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ui_tekstas_vardasKeyReleased(evt);
            }
        });

        ui_mygtukas_pasirinkti.setText("Pasiringti Faila");
        ui_mygtukas_pasirinkti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ui_mygtukas_pasirinktiActionPerformed(evt);
            }
        });

        ui_mygtukas_importuoti.setText("Importuoti");
        ui_mygtukas_importuoti.setEnabled(false);
        ui_mygtukas_importuoti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ui_mygtukas_importuotiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ui_tekstas_vardas, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ui_mygtukas_importuoti, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ui_mygtukas_pasirinkti, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ui_tekstas_vardas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ui_mygtukas_pasirinkti))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ui_mygtukas_importuoti)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ui_mygtukas_pasirinktiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ui_mygtukas_pasirinktiActionPerformed
        JFileChooser failas = new JFileChooser();
        failas.showOpenDialog(null);
        f = failas.getSelectedFile();
        String path = f.getAbsolutePath();
        ui_tekstas_vardas.setText(path);
        String pavadinimas = ui_tekstas_vardas.getText();
        if (!pavadinimas.trim().equals("")) {
            ui_mygtukas_importuoti.setEnabled(true);
        } else {
            ui_mygtukas_importuoti.setEnabled(false);
        }
    }//GEN-LAST:event_ui_mygtukas_pasirinktiActionPerformed

    private void ui_mygtukas_importuotiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ui_mygtukas_importuotiActionPerformed
        String line;

        try (BufferedReader br = new BufferedReader(new FileReader(f))) {
            while ((line = br.readLine()) != null) {
                String[] strings = line.split(" ");
                abs.pridetiDestytoja(Integer.parseInt(strings[0]), strings[1], strings[2]);
            }
        } catch (IOException e) {
        }
        this.dispose();
    }//GEN-LAST:event_ui_mygtukas_importuotiActionPerformed

    private void ui_tekstas_vardasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ui_tekstas_vardasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ui_tekstas_vardasActionPerformed

    private void ui_tekstas_vardasKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ui_tekstas_vardasKeyReleased

    }//GEN-LAST:event_ui_tekstas_vardasKeyReleased

    private void ui_tekstas_vardasPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_ui_tekstas_vardasPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_ui_tekstas_vardasPropertyChange

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ui_mygtukas_importuoti;
    private javax.swing.JButton ui_mygtukas_pasirinkti;
    private javax.swing.JTextField ui_tekstas_vardas;
    // End of variables declaration//GEN-END:variables
}
