/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab2;

import ds.AktyvumoBaluSistema;
import ds.Destytojas;

/**
 *
 * @author pc
 */
public class DestytojaiForm extends javax.swing.JFrame {

    private AktyvumoBaluSistema abs;

    /**
     * Creates new form DestytojaiForm
     */
    public DestytojaiForm(AktyvumoBaluSistema ab) {
        initComponents();
        abs = ab;
    }

    @Override
    public void setVisible(boolean b) {
        super.setVisible(b); //To change body of generated methods, choose Tools | Templates.
        Atnaujinti();
    }

    public void Atnaujinti() {
        Object[][] destytojai = new Object[abs.GautiDestytojuSkaiciu()][3];
        int nr = 0;
        Object kodas, vardas, pavarde;
        for (Object o : abs.getDestytojai()) {
            kodas = ((Destytojas) o).getKodas();
            vardas = ((Destytojas) o).getVardas();
            pavarde = ((Destytojas) o).getPavarde();
            destytojai[nr] = new Object[]{kodas, vardas, pavarde};
            nr++;
        }
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                destytojai,
                new String[]{
                    "Kodas", "Vardas", "Pavarde"
                }
        ));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        pasalinti = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kodas", "Vardas", "Pavarde"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        pasalinti.setText("Šalinti destytoja");
        pasalinti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pasalintiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pasalinti)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(108, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pasalinti)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pasalintiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pasalintiActionPerformed
        if (!abs.getDestytojai().isEmpty()) {
            DestytojoIstrynimas destImport = new DestytojoIstrynimas(this, abs, this);
            destImport.setVisible(true);
        }
    }//GEN-LAST:event_pasalintiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton pasalinti;
    // End of variables declaration//GEN-END:variables
}
