package lab2;

import ds.AktyvumoBaluSistema;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author pc
 */
public class FrameUIAdmin extends javax.swing.JFrame {
    private AktyvumoBaluSistema abs;
    DestytojaiForm destytojuSarasas;
    GrupesSarasas grupSarasas;
    KursuSarasas kursSarasas;
    
    /**
     * Creates new form FrameUI
     */
    public FrameUIAdmin(AktyvumoBaluSistema b) {
       
        
        //jTextField1.setText(abs.getDestytojas().getVardas()+ " " + abs.getDestytojas().getPavarde());
        initComponents();
        abs = b;
         destytojuSarasas = new DestytojaiForm(abs);
         grupSarasas = new GrupesSarasas(abs);
         kursSarasas = new KursuSarasas(abs);
       // jTextField1.setText(abs.getDestytojas().getVardas()+ " " + abs.getDestytojas().getPavarde());

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        pridetiDestytoja = new javax.swing.JMenuItem();
        destytojuPerziura = new javax.swing.JMenuItem();
        importuotiDestytojus = new javax.swing.JMenuItem();
        exportuotiDestytojus = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        pridetiGrupe = new javax.swing.JMenuItem();
        grupiuSarasas = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        pridetiKursa = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Moodle konkurentas");
        setBackground(new java.awt.Color(153, 204, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setText("Prisijungta kaip: Administratorius");

        jMenu1.setText("Failas");

        jMenuItem1.setText("Baigti darba");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Destytojai");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        pridetiDestytoja.setText("Pridėti destytoja");
        pridetiDestytoja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pridetiDestytojaActionPerformed(evt);
            }
        });
        jMenu2.add(pridetiDestytoja);

        destytojuPerziura.setText("Destytojų peržiūra");
        destytojuPerziura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                destytojuPerziuraActionPerformed(evt);
            }
        });
        jMenu2.add(destytojuPerziura);

        importuotiDestytojus.setText("Importuoti destytojus");
        importuotiDestytojus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                importuotiDestytojusActionPerformed(evt);
            }
        });
        jMenu2.add(importuotiDestytojus);

        exportuotiDestytojus.setText("Exportuoti destytojus");
        exportuotiDestytojus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportuotiDestytojusActionPerformed(evt);
            }
        });
        jMenu2.add(exportuotiDestytojus);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Grupes");

        pridetiGrupe.setText("Pridėti grupe");
        pridetiGrupe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pridetiGrupeActionPerformed(evt);
            }
        });
        jMenu3.add(pridetiGrupe);

        grupiuSarasas.setText("Grupių sąrašas");
        grupiuSarasas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grupiuSarasasActionPerformed(evt);
            }
        });
        jMenu3.add(grupiuSarasas);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Kursai");

        pridetiKursa.setText("Pridėti Kursą");
        pridetiKursa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pridetiKursaActionPerformed(evt);
            }
        });
        jMenu4.add(pridetiKursa);

        jMenuItem2.setText("Kursų sąrašas");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem2);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(234, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(254, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void destytojuPerziuraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_destytojuPerziuraActionPerformed
      destytojuSarasas.setVisible(true);
    }//GEN-LAST:event_destytojuPerziuraActionPerformed

    private void pridetiDestytojaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pridetiDestytojaActionPerformed
        DestytojoPridejimas destPrid = new DestytojoPridejimas(this, abs);
        destPrid.setVisible(true);
    }//GEN-LAST:event_pridetiDestytojaActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed

    }//GEN-LAST:event_jMenu2ActionPerformed

    private void exportuotiDestytojusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportuotiDestytojusActionPerformed
        DestytojoExport destExport = new DestytojoExport(this, abs);
        destExport.setVisible(true);
    }//GEN-LAST:event_exportuotiDestytojusActionPerformed

    private void importuotiDestytojusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_importuotiDestytojusActionPerformed
        DestytojoImport destImport = new DestytojoImport(this, abs);
        destImport.setVisible(true);
    }//GEN-LAST:event_importuotiDestytojusActionPerformed

    private void grupiuSarasasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grupiuSarasasActionPerformed
         grupSarasas.setVisible(true);
    }//GEN-LAST:event_grupiuSarasasActionPerformed

    private void pridetiGrupeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pridetiGrupeActionPerformed
        GrupePridejimas pridetiGrupe = new GrupePridejimas(this, abs);
        pridetiGrupe.setVisible(true);
    }//GEN-LAST:event_pridetiGrupeActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        kursSarasas.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void pridetiKursaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pridetiKursaActionPerformed
       KursoPridejimas pridetiKursa = new KursoPridejimas(this, abs);
       pridetiKursa.setVisible(true);
    }//GEN-LAST:event_pridetiKursaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameUIAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameUIAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameUIAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameUIAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
 
      
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem destytojuPerziura;
    private javax.swing.JMenuItem exportuotiDestytojus;
    private javax.swing.JMenuItem grupiuSarasas;
    private javax.swing.JMenuItem importuotiDestytojus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem pridetiDestytoja;
    private javax.swing.JMenuItem pridetiGrupe;
    private javax.swing.JMenuItem pridetiKursa;
    // End of variables declaration//GEN-END:variables
}
