/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab2;

import ds.AktyvumoBaluSistema;
import ds.Grupe;
import java.util.ArrayList;

/**
 *
 * @author pc
 */
public class GrupesSarasas extends javax.swing.JFrame {
    
    private AktyvumoBaluSistema abs;
    
    /**
     * Creates new form GrupesSarasas
     */
    public GrupesSarasas(AktyvumoBaluSistema ab) {
        initComponents();
        abs = ab;
    }

    @Override
    public void setVisible(boolean b) {
        super.setVisible(b); //To change body of generated methods, choose Tools | Templates.
        Atnaujinti();
    }
    
    public void Atnaujinti(){
      if(!abs.getGrupes().isEmpty()){
        Object[][] grupes = new Object[abs.getGrupes().size()][2];
        int nr = 0;
        Object metai, kodas;
        for(Object o: abs.getGrupes()){
            metai = ((Grupe)o).getStojimoMetai();
            kodas = ((Grupe)o).getKodas();
            grupes[nr] = new Object[]{metai, kodas};
                    nr++;
        }
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            grupes,
            new String [] {
                 "Stojimo Metai", "Kodas"
            }
        ));
      }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        ui_tesktas_info = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Stojimo metai", "Kodas"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("Grupių sąrašas:");

        ui_tesktas_info.setText("Detalesnė informacija");
        ui_tesktas_info.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ui_tesktas_infoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ui_tesktas_info)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ui_tesktas_info)
                .addGap(5, 5, 5))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ui_tesktas_infoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ui_tesktas_infoActionPerformed
        GrupesInformacija grupesInfo = new GrupesInformacija(this, abs);
        grupesInfo.setVisible(true);
    }//GEN-LAST:event_ui_tesktas_infoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton ui_tesktas_info;
    // End of variables declaration//GEN-END:variables
}
