/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab2;

import ds.AktyvumoBaluSistema;

/**
 *
 * @author pc
 */
public class GrupePridejimas extends javax.swing.JDialog {

    private AktyvumoBaluSistema abs;

    /**
     * Creates new form GrupePridejimas
     */
    public GrupePridejimas(java.awt.Frame parent, AktyvumoBaluSistema ab) {
        super(parent, true);
        abs = ab;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        l_metai = new javax.swing.JLabel();
        l_kodas = new javax.swing.JLabel();
        f_metai = new javax.swing.JTextField();
        f_kodas = new javax.swing.JTextField();
        patvirtinti = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Grupės pridėjimas");

        l_metai.setText("Metai:");

        l_kodas.setText("Grupės kodas:");

        f_metai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f_metaiActionPerformed(evt);
            }
        });
        f_metai.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                f_metaiKeyReleased(evt);
            }
        });

        f_kodas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                f_kodasKeyReleased(evt);
            }
        });

        patvirtinti.setText("Patvirtinti");
        patvirtinti.setEnabled(false);
        patvirtinti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patvirtintiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(l_metai)
                            .addComponent(l_kodas))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(f_metai)
                            .addComponent(f_kodas, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))))
                .addContainerGap(66, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(patvirtinti)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l_metai)
                    .addComponent(f_metai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l_kodas)
                    .addComponent(f_kodas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(patvirtinti)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void f_metaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f_metaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_f_metaiActionPerformed

    private void f_metaiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_f_metaiKeyReleased
        try {
            int kodas = Integer.parseInt(f_metai.getText());
            if (f_metai.getText().length() != 0 && f_metai.getText().length() == 4 && f_kodas.getText().length() != 0 && f_kodas.getText().length() <= 40) {
                patvirtinti.setEnabled(true);
            } else {
                patvirtinti.setEnabled(false);
            }
        } catch (NumberFormatException e) {
            patvirtinti.setEnabled(false);
        }

    }//GEN-LAST:event_f_metaiKeyReleased

    private void f_kodasKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_f_kodasKeyReleased
       try {
            int kodas = Integer.parseInt(f_metai.getText());
            if (f_metai.getText().length() != 0 && f_metai.getText().length() == 4 && f_kodas.getText().length() != 0 && f_kodas.getText().length() <= 40) {
                patvirtinti.setEnabled(true);
            } else {
                patvirtinti.setEnabled(false);
            }
        } catch (NumberFormatException e) {
            patvirtinti.setEnabled(false);
        }
    }//GEN-LAST:event_f_kodasKeyReleased

    private void patvirtintiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patvirtintiActionPerformed
        String kodas = f_kodas.getText();
        String metai = f_metai.getText();
        abs.pridetiGrupe(Integer.parseInt(metai), kodas);
        this.dispose();
    }//GEN-LAST:event_patvirtintiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField f_kodas;
    private javax.swing.JTextField f_metai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel l_kodas;
    private javax.swing.JLabel l_metai;
    private javax.swing.JButton patvirtinti;
    // End of variables declaration//GEN-END:variables
}
