/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab2;

import ds.AktyvumoBaluSistema;
import ds.Grupe;
import ds.Studentas;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author pc
 */
public class GrupesInformacija extends javax.swing.JDialog {

    private AktyvumoBaluSistema abs;

    /**
     * Creates new form GrupesInformacija
     */
    public GrupesInformacija(java.awt.Frame parent, AktyvumoBaluSistema ab) {
        super(parent, true);
        abs = ab;
        initComponents();
        dropdown.setModel(new DefaultComboBoxModel(abs.getGrupes().toArray()));
        prideti.setEnabled(false);
        Atnaujinti();
        // jComboBox1.setModel(new DefaultComboBoxModel(abs.gautiGrupe(dropdown.getSelectedItem().toString()).getStudentai().toArray()));
    }

    public void Atnaujinti() {
        if (dropdown.getSelectedIndex() != -1 && !abs.getGrupes().isEmpty()) {
            Object[][] Studentai = new Object[(abs.gautiGrupe(dropdown.getSelectedItem().toString())).getStudentai().size()][3];
            int nr = 0;
            Object kodas, vardas, pavarde;
            for (Object o : abs.gautiGrupe(dropdown.getSelectedItem().toString()).getStudentai()) {
                kodas = ((Studentas) o).getKodas();
                vardas = ((Studentas) o).getVardas();
                pavarde = ((Studentas) o).getPavarde();
                Studentai[nr] = new Object[]{kodas, vardas, pavarde};
                nr++;
            }
            studLentele.setModel(new javax.swing.table.DefaultTableModel(
                    Studentai,
                    new String[]{
                        "Studento Kodas", "Vardas", "Pavardė"
                    }
            ));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dropdown = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        studLentele = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        l_kodas = new javax.swing.JLabel();
        l_vardas = new javax.swing.JLabel();
        l_pavarde = new javax.swing.JLabel();
        f_kodas = new javax.swing.JTextField();
        f_vardas = new javax.swing.JTextField();
        f_pavarde = new javax.swing.JTextField();
        prideti = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        dropdown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        dropdown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dropdownActionPerformed(evt);
            }
        });

        studLentele.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Studento Kodas", "Vardas", "Pavarde"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(studLentele);

        jLabel1.setText("Detalesnė informacija");

        jLabel2.setText("Grupė:");

        jLabel3.setText("Pridėti studentą");

        l_kodas.setText("Kodas:");

        l_vardas.setText("Vardas:");

        l_pavarde.setText("Pavardė:");

        f_kodas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f_kodasActionPerformed(evt);
            }
        });
        f_kodas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                f_kodasKeyReleased(evt);
            }
        });

        f_vardas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f_vardasActionPerformed(evt);
            }
        });
        f_vardas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                f_vardasKeyReleased(evt);
            }
        });

        f_pavarde.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                f_pavardeKeyReleased(evt);
            }
        });

        prideti.setText("Pridėti");
        prideti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pridetiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addContainerGap(286, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(l_pavarde)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(f_pavarde))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(11, 11, 11)
                                        .addComponent(l_kodas))
                                    .addComponent(l_vardas, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(f_kodas, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(f_vardas, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addComponent(prideti)))
                .addGap(0, 15, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(dropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l_kodas)
                    .addComponent(f_kodas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(f_vardas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l_vardas)
                    .addComponent(prideti))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l_pavarde)
                    .addComponent(f_pavarde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dropdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dropdownActionPerformed
        Atnaujinti();
    }//GEN-LAST:event_dropdownActionPerformed

    private void pridetiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pridetiActionPerformed
        if (dropdown.getSelectedIndex() != -1 && !abs.getGrupes().isEmpty()) {
            String kodas = f_kodas.getText();
            String vardas = f_vardas.getText();
            String pavarde = f_pavarde.getText();
            Studentas studentas = new Studentas(Integer.parseInt(kodas), vardas, pavarde);
            Grupe grupe = abs.gautiGrupe(dropdown.getSelectedItem().toString());
            abs.priskirtiStudentaPrieGrupes(grupe, studentas);
            Atnaujinti();
        }
    }//GEN-LAST:event_pridetiActionPerformed

    private void f_vardasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f_vardasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_f_vardasActionPerformed

    private void f_kodasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f_kodasActionPerformed
        try {
            int kodas = Integer.parseInt(f_kodas.getText());
            if (f_vardas.getText().length() != 0 && f_vardas.getText().length() <= 40 && f_pavarde.getText().length() != 0 && f_pavarde.getText().length() <= 40) {
                prideti.setEnabled(true);
            } else {
                prideti.setEnabled(false);
            }
        } catch (NumberFormatException e) {
            prideti.setEnabled(false);
        }
    }//GEN-LAST:event_f_kodasActionPerformed

    private void f_kodasKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_f_kodasKeyReleased
        try {
            int kodas = Integer.parseInt(f_kodas.getText());
            if (f_vardas.getText().length() != 0 && f_vardas.getText().length() <= 40 && f_pavarde.getText().length() != 0 && f_pavarde.getText().length() <= 40) {
                prideti.setEnabled(true);
            } else {
                prideti.setEnabled(false);
            }
        } catch (NumberFormatException e) {
            prideti.setEnabled(false);
        }
    }//GEN-LAST:event_f_kodasKeyReleased

    private void f_vardasKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_f_vardasKeyReleased
        try {
            int kodas = Integer.parseInt(f_kodas.getText());
            if (f_vardas.getText().length() != 0 && f_vardas.getText().length() <= 40 && f_pavarde.getText().length() != 0 && f_pavarde.getText().length() <= 40) {
                prideti.setEnabled(true);
            } else {
                prideti.setEnabled(false);
            }
        } catch (NumberFormatException e) {
            prideti.setEnabled(false);
        }
    }//GEN-LAST:event_f_vardasKeyReleased

    private void f_pavardeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_f_pavardeKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_f_pavardeKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GrupesInformacija.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GrupesInformacija.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GrupesInformacija.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GrupesInformacija.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> dropdown;
    private javax.swing.JTextField f_kodas;
    private javax.swing.JTextField f_pavarde;
    private javax.swing.JTextField f_vardas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel l_kodas;
    private javax.swing.JLabel l_pavarde;
    private javax.swing.JLabel l_vardas;
    private javax.swing.JButton prideti;
    private javax.swing.JTable studLentele;
    // End of variables declaration//GEN-END:variables
}
