/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab2;

import ds.AktyvumoBaluSistema;
import ds.Destytojas;
import ds.Grupe;
import ds.Kursas;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author pc
 */
public class KursoInformacija extends javax.swing.JDialog {

    private AktyvumoBaluSistema abs;

    /**
     * Creates new form KursoInformacija
     */
    public KursoInformacija(java.awt.Frame parent, AktyvumoBaluSistema ab) {
        super(parent, true);
        abs = ab;
        initComponents();
        dropdown_kursas.setModel(new DefaultComboBoxModel(abs.getKursai().toArray()));
        dropdown_destytojas.setModel(new DefaultComboBoxModel(abs.getDestytojai().toArray()));
        dropdown_grupe.setModel(new DefaultComboBoxModel(abs.getGrupes().toArray()));
        AtnaujintiAprasyma();
    }

    public void AtnaujintiAprasyma() {
        if (dropdown_kursas.getSelectedIndex() != -1 && !abs.getKursai().isEmpty()) {
            String strings[];
            strings = dropdown_kursas.getSelectedItem().toString().split(" ");
            testarea.setText(abs.gautiKursa(strings[1].substring(1, strings[1].length() - 1)).getAprasas());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        dropdown_kursas = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        testarea = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        dropdown_destytojas = new javax.swing.JComboBox<>();
        prideti_destytoja = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        dropdown_grupe = new javax.swing.JComboBox<>();
        prideti_grupe = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Kurso informacija");

        jLabel2.setText("Kursas:");

        dropdown_kursas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        dropdown_kursas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dropdown_kursasActionPerformed(evt);
            }
        });

        jLabel3.setText("Kurso informacija:");

        testarea.setColumns(20);
        testarea.setRows(5);
        jScrollPane1.setViewportView(testarea);

        jLabel4.setText("Pridėti destytoja");

        jLabel5.setText("Destytojas:");

        dropdown_destytojas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        dropdown_destytojas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dropdown_destytojasActionPerformed(evt);
            }
        });

        prideti_destytoja.setText("Pridėti");
        prideti_destytoja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prideti_destytojaActionPerformed(evt);
            }
        });

        jLabel6.setText("Pridėti grupę");

        jLabel7.setText("Grupė:");

        dropdown_grupe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        prideti_grupe.setText("Pridėti");
        prideti_grupe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prideti_grupeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dropdown_kursas, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3)
                    .addComponent(jLabel6)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(dropdown_destytojas, 0, 119, Short.MAX_VALUE)
                            .addComponent(dropdown_grupe, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(prideti_destytoja)
                            .addComponent(prideti_grupe))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(dropdown_kursas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(dropdown_destytojas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(prideti_destytoja)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(dropdown_grupe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prideti_grupe))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dropdown_destytojasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dropdown_destytojasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dropdown_destytojasActionPerformed

    private void dropdown_kursasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dropdown_kursasActionPerformed
        AtnaujintiAprasyma();
    }//GEN-LAST:event_dropdown_kursasActionPerformed

    private void prideti_destytojaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prideti_destytojaActionPerformed
        if (!abs.getDestytojai().isEmpty()) {
            String[] destytojasString = dropdown_destytojas.getSelectedItem().toString().split(" ");
            String[] kursasString = dropdown_kursas.getSelectedItem().toString().split(" ");

            Destytojas destytojas = abs.gautiDestytoja(Integer.parseInt(destytojasString[2].substring(1, destytojasString[2].length() - 1)));
            Kursas kursas = abs.gautiKursa(kursasString[1].substring(1, kursasString[1].length() - 1));
            System.out.print(kursasString[1].substring(1, kursasString[1].length() - 1));
            System.out.print(Integer.parseInt(destytojasString[2].substring(1, destytojasString[2].length() - 1)));
            abs.priskirtiDestytojaPrieKurso(destytojas, kursas);
        }


    }//GEN-LAST:event_prideti_destytojaActionPerformed

    private void prideti_grupeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prideti_grupeActionPerformed
        if (!abs.getGrupes().isEmpty()) {
            String[] kursasString = dropdown_kursas.getSelectedItem().toString().split(" ");
            Kursas kursas = abs.gautiKursa(kursasString[1].substring(1, kursasString[1].length() - 1));
            Grupe grupe = abs.gautiGrupe(dropdown_grupe.getSelectedItem().toString());
            abs.priskirtiGrupePrieKurso(grupe, kursas);

        }
    }//GEN-LAST:event_prideti_grupeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KursoInformacija.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KursoInformacija.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KursoInformacija.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KursoInformacija.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> dropdown_destytojas;
    private javax.swing.JComboBox<String> dropdown_grupe;
    private javax.swing.JComboBox<String> dropdown_kursas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton prideti_destytoja;
    private javax.swing.JButton prideti_grupe;
    private javax.swing.JTextArea testarea;
    // End of variables declaration//GEN-END:variables
}
