/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab2;

import ds.AktyvumoBaluSistema;

/**
 *
 * @author pc
 */
public class KursoPridejimas extends javax.swing.JDialog {
     private AktyvumoBaluSistema abs;
    /**
     * Creates new form KursoPridejimas
     */
    public KursoPridejimas(java.awt.Frame parent, AktyvumoBaluSistema ab) {
        super(parent, true);
        abs = ab;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        l_pavadinimas = new javax.swing.JLabel();
        l_trumpasPav = new javax.swing.JLabel();
        l_aprasymas = new javax.swing.JLabel();
        f_pavadinimas = new javax.swing.JTextField();
        f_trumpasPav = new javax.swing.JTextField();
        f_aprasymas = new javax.swing.JTextField();
        prideti = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Kurso Pridėjimas");

        l_pavadinimas.setText("Pavadinimas:");

        l_trumpasPav.setText("Trumpas pavadinimas:");
        l_trumpasPav.setToolTipText("");

        l_aprasymas.setText("Aprašymas:");

        f_pavadinimas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f_pavadinimasActionPerformed(evt);
            }
        });
        f_pavadinimas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                f_pavadinimasKeyReleased(evt);
            }
        });

        f_trumpasPav.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                f_trumpasPavKeyReleased(evt);
            }
        });

        f_aprasymas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                f_aprasymasKeyReleased(evt);
            }
        });

        prideti.setText("Pridėti");
        prideti.setEnabled(false);
        prideti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pridetiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(l_trumpasPav)
                            .addComponent(l_pavadinimas)
                            .addComponent(l_aprasymas))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(f_pavadinimas)
                            .addComponent(f_trumpasPav)
                            .addComponent(f_aprasymas, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE))))
                .addContainerGap(100, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(prideti)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l_pavadinimas)
                    .addComponent(f_pavadinimas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l_trumpasPav)
                    .addComponent(f_trumpasPav, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l_aprasymas)
                    .addComponent(f_aprasymas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(prideti)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void f_pavadinimasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f_pavadinimasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_f_pavadinimasActionPerformed

    private void f_pavadinimasKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_f_pavadinimasKeyReleased

        if(f_pavadinimas.getText().length()!=0 && f_pavadinimas.getText().length() <=40 && f_trumpasPav.getText().length()!=0 && f_trumpasPav.getText().length() <=40 && f_aprasymas.getText().length()!=0 && f_aprasymas.getText().length() <=250){
            prideti.setEnabled(true);
        }
        else {
            prideti.setEnabled(false);
        }
    }//GEN-LAST:event_f_pavadinimasKeyReleased

    private void f_trumpasPavKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_f_trumpasPavKeyReleased

        if(f_pavadinimas.getText().length()!=0 && f_pavadinimas.getText().length() <=40 && f_trumpasPav.getText().length()!=0 && f_trumpasPav.getText().length() <=40 && f_aprasymas.getText().length()!=0 && f_aprasymas.getText().length() <=250){
            prideti.setEnabled(true);
        }
        else {
            prideti.setEnabled(false);
        }
    }//GEN-LAST:event_f_trumpasPavKeyReleased

    private void f_aprasymasKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_f_aprasymasKeyReleased

        if(f_pavadinimas.getText().length()!=0 && f_pavadinimas.getText().length() <=40 && f_trumpasPav.getText().length()!=0 && f_trumpasPav.getText().length() <=40 && f_aprasymas.getText().length()!=0 && f_aprasymas.getText().length() <=250){
            prideti.setEnabled(true);
        }
        else {
            prideti.setEnabled(false);
        }
    }//GEN-LAST:event_f_aprasymasKeyReleased

    private void pridetiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pridetiActionPerformed
        String pavadinimas = f_pavadinimas.getText();
        String trumpaspavadinimas = f_trumpasPav.getText();
        String trumpasaprasymas = f_aprasymas.getText();
        abs.pridetiKursa(pavadinimas, trumpaspavadinimas, trumpasaprasymas);
        this.dispose(); 
    }//GEN-LAST:event_pridetiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KursoPridejimas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KursoPridejimas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KursoPridejimas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KursoPridejimas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
      
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField f_aprasymas;
    private javax.swing.JTextField f_pavadinimas;
    private javax.swing.JTextField f_trumpasPav;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel l_aprasymas;
    private javax.swing.JLabel l_pavadinimas;
    private javax.swing.JLabel l_trumpasPav;
    private javax.swing.JButton prideti;
    // End of variables declaration//GEN-END:variables
}
